name: MYX4567/distilgpt2-finetuned-wikitext2
class_name: GPT2LMHeadModel
tokenizer_class: GPT2TokenizerFast
tokenizer_name: distilgpt2
inner_params:
- transformer.h.3.mlp.c_fc.weight
- transformer.h.3.mlp.c_proj.weight
- transformer.h.4.mlp.c_fc.weight
- transformer.h.4.mlp.c_proj.weight
- transformer.h.5.mlp.c_fc.weight
- transformer.h.5.mlp.c_proj.weight

