name: gpt2-xl
class_name: GPT2LMHeadModel
tokenizer_class: GPT2TokenizerFast
tokenizer_name: gpt2-xl
inner_params:
- transformer.h.45.mlp.c_proj.weight
- transformer.h.45.mlp.c_fc.weight
- transformer.h.46.mlp.c_proj.weight
- transformer.h.46.mlp.c_fc.weight
- transformer.h.47.mlp.c_proj.weight
- transformer.h.47.mlp.c_fc.weight
