name: gpt2-large
class_name: GPT2LMHeadModel
tokenizer_class: GPT2TokenizerFast
tokenizer_name: gpt2-large
inner_params:
- transformer.h.33.mlp.c_proj.weight
- transformer.h.33.mlp.c_fc.weight
- transformer.h.34.mlp.c_proj.weight
- transformer.h.34.mlp.c_fc.weight
- transformer.h.35.mlp.c_proj.weight
- transformer.h.35.mlp.c_fc.weight
