name: google/t5-small-ssm-nq
class_name: AutoModelForSeq2SeqLM
tokenizer_class: AutoTokenizer
tokenizer_name: google/t5-small-ssm-nq
inner_params:
- encoder.block.6.layer.1.DenseReluDense.wi_0.weight
- encoder.block.6.layer.1.DenseReluDense.wo.weight
- encoder.block.7.layer.1.DenseReluDense.wi_0.weight
- encoder.block.7.layer.1.DenseReluDense.wo.weight
- decoder.block.6.layer.2.DenseReluDense.wi_0.weight
- decoder.block.6.layer.2.DenseReluDense.wo.weight
- decoder.block.7.layer.2.DenseReluDense.wi_0.weight
- decoder.block.7.layer.2.DenseReluDense.wo.weight

pt: null